name: Build all versions
on:
  push:
    branches:
      - '!master'
jobs:
  BuildAll:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        arch: [ia32, x64]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - name: Install OS Dependencies
      if: ${{ runner.os == 'Linux' && matrix.arch == 'x64' }}
      run: sudo apt-get install libxtst-dev libpng++-dev gcc-multilib g++-multilib -y
    - name: Install OS Dependencies (32-bit)
      if: ${{ runner.os == 'Linux' && matrix.arch == 'ia32' }}
      run: sudo apt-get install libxtst-dev:i386 libpng++-dev:i386 gcc-multilib g++-multilib -y
    - name: Install dependencies
      run: npm ci
    - name: Prebuild Node
      run: npx prebuild -t 16.13.0 -t 14.18.1 --arch=${{ matrix.arch }}
    - name: Prebuild Latest Electron
      run: npx prebuild -t 16.0.0 -t 15.3.2 -t 14.2.1 -t 13.6.1 -r electron --arch=${{ matrix.arch }}
